### ISSUE TITLE
Can not connect to es in container

### ISSUE THREAD

**Issue by zhuguoliang** [olivere/elastic#824]
Please use the following questions as a guideline to help me answer
your issue/question without further inquiry. Thank you.

### Which version of Elastic are you using?

[ ] elastic.v2 (for Elasticsearch 1.x)
[ ] elastic.v3 (for Elasticsearch 2.x)
[ ] elastic.v5 (for Elasticsearch 5.x)
[ x] elastic.v6 (for Elasticsearch 6.x)

### Please describe the expected behavior
Discover es service in docker

### Please describe the actual behavior
I want to use docker-compose to run search app in one container and es in another container.

I can do the following in search app container to check es status.

> curl http://172.21.0.2:9200/_nodes/http?pretty

However, I can't connect to es in the container.

> health check timeout: Head http://172.21.0.2:9200: dial tcp 172.21.0.2:9200: connect: connection refused: no Elasticsearch node available

Note that I can still execute the search app directly from host, it can connect to es successfully.

### Any steps to reproduce the behavior?
docker-compose yaml file

```
version: '3.5'
services:
  search_api:
    container_name: 'search_api'
    build: '../src/search-api'
    restart: 'on-failure'
    ports:
      - '8080:8080'
    depends_on:
      - elasticsearch
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.2.3'
    ports:
      - '9200:9200'
      - '9300:9300'

```
Dockerfile for search app

```
FROM golang:1.10.0

RUN adduser --disabled-password --gecos '' api
USER api

WORKDIR /go/src/app
COPY . .

RUN go install -v ./...

CMD [ "app" ]
```
Code connecting to es:
```
 20                 elasticClient, err = elastic.NewClient(
 21                         //elastic.SetURL("http://elasticsearch:9200"),
 22                         elastic.SetURL("http://172.21.0.2:9200"),
 23                         elastic.SetSniff(false),

```
